// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rifadbinrjfzftngnhsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpZmFkYmlucmpmemZ0bmduaHNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3NTYwMTgsImV4cCI6MjA1NTMzMjAxOH0.Y87NsgNJT8J7AIjY9TBbkq6YlZseRiheWLeVJJl8kPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);